# Basic

## Markdown
    - 텍스트 기반의 마크업(Mark-up)언어
    - HTML로 변환 가능
    - 간단한 구조 문법을 사용하여 웹용 컨텐츠를 빠르게 제작 가능

### Contents
    1. 제목
    2. 점
    3. 수평선
    4. 코드 강조
    5. 수식
    6. 링크/이미지

#### 1. 제목
    - Head 작성시에는 html 태그인 <h1>등과 같은 방식 사용 가능
    - #을 이용하여 작성할 경우 최대 6개까지 가능


<h1>H1</h1>
<h5>H5</h5>

#### 2. 점
    - 항목을 표기할 때 사용하는 방법으로 다양한 점 모양을 사용할 수 있음
    - 주로 사용하는 점 표기 방식: - + *

- -표기
    + +표기
        * *표기

#### 3. 수평선
    - 선 표기는 -나 * 기호를 길게 붙여주면 표시됨

#### 4. 코드강조
    - 마크다운에서 코드 표기 방식을 작성할 때 표현하고자 하는 언어의 방식으로 표시가 가능
    - 작성시 ``` ``` 를 이용하여 작성
    (예시)
```python
from sklearn.linear import LinearRegression

lr_m = LinearRegression()
```


#### 5. 수식
    - LaTex 기반의 수식 작성이 가능
    - 쟉성 시 $ $ 기호를 이용하여 표시
    (예시)
$\sqrt{2}=1.41\cdots$
$\alpha : \rm{Variant\ constance}$

$
    \begin{pmatrix}
    1 & 2 & 3 \\
    \end{pmatrix}
$

#### 6. 링크/이미지
    - 외부 참조용 이미지나 링크를 불러서 사용할 수 있으며 이미지 자체에 하이퍼링크 삽입이 가능
    - ![이미지이름](이미지링크) 형식으로 작성
    - 이미지에 링크를 삽입하고 싶을 경우 html의 <a> 태그 활용

<a href="https://www.youtube.com/watch?v=YQ3kc8Hrwhg&list=PLd_62qz_v9RnXClsfA-S8oQIo8klXC_jg&pp=gAQBiAQB">![Unboxing](https://i.ytimg.com/vi/YQ3kc8Hrwhg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCaFq-RGQKgevwxFK8rUCXTghYQEg)</a>

## Code

### 기본 작성법
    - Jupyter Lab이나 Jupyter notebook(ipython)의 경우 Markdown과 Code 작성 상태가 존재
    - 일반적으로 코드를 구현하는 모드

In [1]:
### 주석처리는 #을 이용하여 작성
""" \"\"\"을 이용하여 작성하는 방법도 존재""" # docstring

print("Text") # 가장 기본적으로 결과를 출력하는 방식
"""마지막 줄을 출력하고 싶을때엔 "print" 생략 가능"""

Text


'마지막 줄을 출력하고 싶을때엔 "print" 생략 가능'

### 선언
    - 일반적으로 식별자(변수명)를 작성하고 =을 이용하여 선언
    - 파이썬은 데이터 타입을 지정할 필요가 없음
        * 데이터타입: 문자형, 숫자(정수, 실수)형, 논리형 등

In [4]:
num = "3" # 문자열
num, type(num)

('3', str)

In [3]:
type(int(num))

int

In [5]:
int(num)

3

In [6]:
type(num)

str

In [7]:
num = int(num)
type(num)

int

In [ ]:
# int, str, float, boolean(True, False),

### 자료형 구조
    - 리스트, 튜플, 딕셔너리, 집합 등
    - 일반적으로 자료를 많이 담는 구조는 리스트
    - 튜플은 내부 데이터 수정 불가능
    - 딕셔너리/집합은 index가 없음

In [8]:
ls = [1, 2, 3]

In [9]:
ls[1] # python은 0부터 순서 부여

2

In [10]:
tp = (1, 2, 3)

In [11]:
tp[2] # index로 호출

3

In [14]:
dic = {
    "key":"value"
}
dic

{'key': 'value'}

In [15]:
dic2 = {
    "key":["value1", "value2"]
}
dic2

{'key': ['value1', 'value2']}

In [16]:
ls2 = [1, 2, 3, "사", "five"]
ls2

[1, 2, 3, '사', 'five']

In [18]:
print(dic2.keys()) # key값만 출력
print(dic2.values()) # value값만 출력
print(dic2.items()) # key, value 출력

dict_keys(['key'])
dict_values([['value1', 'value2']])
dict_items([('key', ['value1', 'value2'])])


In [19]:
dic3 = {
    'k1':[1, 2, 3],
    'k2':[4, 5, 6],
    'k3':[7, 8, 9]
}

In [21]:
dic3['k2'] # key값으로 value 호출

[4, 5, 6]

#### 데이터 변경
    - 리스트 타입의 경우 index를 이용한 변경
    - 딕셔너리 타입의 경우 key를 이용한 변경
    - 튜플은 선언한 값에 대하여 변경 불가능

In [ ]:
# list, tuple 차이점 - 데이터 변경 가능/불가능
ls[1] = 5
ls

[1, 5, 3]

In [ ]:
tp[2] = 10
tp # tuple은 데이터 변경 불가

TypeError: 'tuple' object does not support item assignment

In [22]:
dic["key"] = ['val1', 'val2'] # key값으로 데이터 변경
dic

{'key': ['val1', 'val2']}

### 데이터 출력
    - 기본 출력구문: print()
    - 자료형의 경우 offset index, dictionary의 경우 key, value 등을 활용
    - index가 존재하는 자료형의 경우 slicing 방법을 통한 출력

In [23]:
print("Hello, World")

Hello, World


In [24]:
dic3

{'k1': [1, 2, 3], 'k2': [4, 5, 6], 'k3': [7, 8, 9]}

In [27]:
# slicing
import numpy as np
sp = np.random.randint(1, 1000, 100)
sp

array([169, 904, 155, 820, 843, 436, 119, 231, 626, 671, 229, 518,  20,
       389, 735,  78, 343, 444, 602,  23, 370, 921, 706, 300, 651, 849,
       636, 411, 908, 298,  68, 208, 505, 554, 899, 899, 119, 227, 303,
       554,  18, 965, 453, 271, 335, 546, 144, 629, 711, 514, 977, 660,
       311, 885, 224, 808, 984, 126,  62, 550, 453, 294, 875, 546, 733,
        95, 405, 370, 454, 601, 413, 190, 376, 266, 405, 158, 804, 808,
       159, 404, 795, 239, 781, 694,  45, 358, 476, 791, 267, 495, 904,
       511, 228, 169, 519, 685, 782, 951, 425, 475])

In [28]:
sp[2:40] # slicing [시작:종료], 종료값은 포함 X

array([155, 820, 843, 436, 119, 231, 626, 671, 229, 518,  20, 389, 735,
        78, 343, 444, 602,  23, 370, 921, 706, 300, 651, 849, 636, 411,
       908, 298,  68, 208, 505, 554, 899, 899, 119, 227, 303, 554])

In [29]:
sp[2:40:5] # [시작:종료:간격]

array([155, 231,  20, 444, 706, 411, 505, 227])

In [31]:
ls3 = [i for i in range(1, 1000, 100)]
ls3

[1, 101, 201, 301, 401, 501, 601, 701, 801, 901]

In [33]:
ls3[:5:-2]

[901, 701]

### 조건문과 반복문
    - 조건문 작성: if, if else, if elif else
    - 반복문 작성: for, while, list conprehension

In [34]:
# 조건문
ls4 = [i for i in range(1, 20)] # list comprehension
ls4

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

```python
if (조건문): # 조건문이 True일 때
    실행문 # 실행
```

In [35]:
if True:
    print("안녕하세요?")

안녕하세요?


In [36]:
if False:
    print("반갑고요?")

In [37]:
if False:
    print("True일 때 실행")
else: # if문이 false면 무조건 실행
    print("False일 때 실행")

False일 때 실행


In [39]:
if False:
    print("IF True")
elif False:
    print("IF False, elif True")
else:
    print("IF False, elif False")

IF False, elif False


In [40]:
# for문
txt = "Pukyong Univ."
for a in txt:
    print(a)

P
u
k
y
o
n
g
 
U
n
i
v
.


In [42]:
for k, v in dic3.items():
    print(f"key: {k}, value: {v}")

key: k1, value: [1, 2, 3]
key: k2, value: [4, 5, 6]
key: k3, value: [7, 8, 9]


In [43]:
for k in dic3.keys():
    print(f"key: {k}") # , value: {v}")

key: k1
key: k2
key: k3


In [46]:
len(ls3), len(ls4)

(10, 19)

In [51]:
for n1, n2 in zip(ls3, num):
    print(f"n1: {n1}, n2: {n2}")

TypeError: 'int' object is not iterable

In [52]:
for idx, num in enumerate(ls3): # enumerate: index와 data를 동시에 출력
    print(f"index: {idx}, number: {num}")

index: 0, number: 1
index: 1, number: 101
index: 2, number: 201
index: 3, number: 301
index: 4, number: 401
index: 5, number: 501
index: 6, number: 601
index: 7, number: 701
index: 8, number: 801
index: 9, number: 901


In [53]:
# list comprehension
ls5 = [(idx, num) for idx, num in enumerate(ls3)]
ls5

[(0, 1),
 (1, 101),
 (2, 201),
 (3, 301),
 (4, 401),
 (5, 501),
 (6, 601),
 (7, 701),
 (8, 801),
 (9, 901)]

```python
while (조건문): # 조건문이 True일 때
    실행문 # 실행
```

In [54]:
# while
num = 0

while True:
    print(num)
    num += 1

    if num == 1001:
        break # break: 탈출문

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [55]:
num = 0
while num < 1001:
    print(num)
    num += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [58]:
num = 0
while True:
    if (num % 2) == 0:
        num += 1
        continue # continue를 만나면 다음 루프로 건너뛰기

    print(num)
    num += 1
    if num == 1000:
        break


1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101
103
105
107
109
111
113
115
117
119
121
123
125
127
129
131
133
135
137
139
141
143
145
147
149
151
153
155
157
159
161
163
165
167
169
171
173
175
177
179
181
183
185
187
189
191
193
195
197
199
201
203
205
207
209
211
213
215
217
219
221
223
225
227
229
231
233
235
237
239
241
243
245
247
249
251
253
255
257
259
261
263
265
267
269
271
273
275
277
279
281
283
285
287
289
291
293
295
297
299
301
303
305
307
309
311
313
315
317
319
321
323
325
327
329
331
333
335
337
339
341
343
345
347
349
351
353
355
357
359
361
363
365
367
369
371
373
375
377
379
381
383
385
387
389
391
393
395
397
399
401
403
405
407
409
411
413
415
417
419
421
423
425
427
429
431
433
435
437
439
441
443
445
447
449
451
453
455
457
459
461
463
465
467
469
471
473
475
477
479
481
483
485
487
489
491
493
495
497
499
501
503
505
507
509
511
513
515
517
519
521
523
525
527

### 함수
    - 필요에 따라 반복을 매번 시행하거나 연산을 매번 작성하기 번거로울 때 함수로 선언한 뒤 재사용
    - 객체 지향 언어의 가장 큰 장점
    - 다양한 함수 형태를 생성할 수 있으나 기본적으로 필요한 연산 구성으로 선언하는 것이 일반적

In [60]:
def textdata_input():
    txt = input("텍스트를 입력하세요: ")
    return txt

In [61]:
def text_split(txt): # txt: argument
    return txt.split(" ")

In [62]:
text_split(textdata_input())

텍스트를 입력하세요: 오늘의 점심 메뉴는 마늘닭구이 입니다.


['오늘의', '점심', '메뉴는', '마늘닭구이', '입니다.']

    - 반환된 값을 받아서 연산이 처리되는 로직을 구성하는 것이 중요

#### 전역변수, 지역변수
    - 활성화된 세션내의 변수는 어디서든 사용가능
    - 지역변수: 함수 내부의 변수는 함수 안에서만 사용되고 외부로 뽑아낼 수 없음
    - 전역변수: 외부변수를 함수 내부에서도 사용하고 외부에도 그대로 반영할 수 있도록 선언
        + global 선언

In [3]:
num = 702

def today():
    print(num)

today()

702


In [5]:
num = 702

def tommorow():
    num = 703 # 지역변수
    print(f"tommorow: {num}")

tommorow()

print(f"today: {num}")

tommorow: 703
today: 702


In [7]:
num = 218

def birth():
    global num
    print(f"num: {num}")

    num = 621
    print(f"date: {num}")

birth()

print(f"num: {num}")

num: 218
date: 621
num: 621


#### map 함수
    - 순서가 있는 데이터값에 함수를 모두 적용하여 결과를 출력하는 함수

In [8]:
num_txt = "1 2 3 4 5 6 7 8 9"
num_txt.split(" ")

['1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
num_int = list(map(int, num_txt.split(" "))) # data가 iterable(반복 가능)
num_int

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### 클래스
    - 파이썬에서 모듈화하여 사용하는 대표적인 형태
    - 클래스 내부에 변수, 함수 등을 선언하여 사용
    - 클래스 인스턴스화를 통해 객체지향 프로그래밍

In [31]:
class Study:
    def __init__(self): # 생성자: 클래스 인스턴스 생성 시 자동으로 실행되는 함수
        self.ls = []
        self.student = []
        print(f"Study Class가 생성되었습니다.")

    def join_study(self, name, age, cls):
        self.student.append(name)
        self.student.append(int(age))
        self.student.append(cls)

        self.ls.append(self.student)

        print(f"스터디에 {self.ls[-1]}가 참여하였습니다.")


In [32]:
ml_study = Study() # 클래스 인스턴스 생성

Study Class가 생성되었습니다.


In [33]:
ml_study.join_study("ASK", "20", "Math")

스터디에 ['ASK', 20, 'Math']가 참여하였습니다.


#### 클래스 상속
    - 부모 클래스의 내용을 그대로 받아 사용(상속)
    - 필요에 따라 부모 클래스의 함수나 변수를 변경하여 사용

In [36]:
class GroupStudy(Study):
    def __init__(self):
        super().__init__()
        self.group_ls = []

    def group_est(self, rep):
        self.group_ls.append(rep)
        print(f"스터디 그룹 {self.group_ls[-1]}(이)가 생성되었습니다.")

        if self.ls:
            print("참여자 명단>")
            for p in self.ls:
                print("\t", p[0])
        else:
            print("참여자가 없습니다.")

In [37]:
ml_gstudy = GroupStudy()

Study Class가 생성되었습니다.


In [38]:
ml_gstudy.group_est("Machine Learning")

스터디 그룹 Machine Learning(이)가 생성되었습니다.
참여자가 없습니다.


In [39]:
ml_study.group_est("ML")

AttributeError: 'Study' object has no attribute 'group_est'

In [40]:
ml_gstudy.join_study("ASK", "20", "Math")

스터디에 ['ASK', 20, 'Math']가 참여하였습니다.


In [41]:
ml_gstudy.group_est("Math")

스터디 그룹 Math(이)가 생성되었습니다.
참여자 명단>
	 ASK


### 예외처리
    - Try, Except 구문을 활용하여 예외처리 시행
    - 코드가 예외발생시 정상 종료가 되도록 설정하여 사용

In [43]:
pw = input("비밀번호를 입력하세요: ")
try:
    print(f"비밀번호의 총 합은 {sum(map(int, pw.split(' ')))}입니다.")
except:
    print("올바른 비밀번호 타입이 아닙니다.")

비밀번호를 입력하세요: 1 2 3 사
올바른 비밀번호 타입이 아닙니다.


In [46]:
# try except else, try except finally
pw = input("비밀번호를 입력하세요: ")

try:
    res = sum(map(int, pw.split(" ")))
    print(f"비밀번호의 총 합은 {res}입니다.")
except:
    print("올바른 비밀번호 형식이 아닙니다.")
else: # 정상 실행이 되었음을 확인할 수 있다.
    print("이용해주셔서 감사")

비밀번호를 입력하세요: 1 3 5 칠
올바른 비밀번호 형식이 아닙니다.


In [49]:
pw = input("비밀번호를 입력하세요: ")

try:
    res = sum(map(int, pw.split(" ")))
    # print(f"비밀번호의 총 합은 {res}입니다.")
except:
    print("올바른 비밀번호 형식이 아닙니다.")
else:
    if res < 40:
        print("총 합이 조건에 미치지 않으므로 실행할 수 없습니다.")
    else:
        print("Unlocked")
finally:
    print("이용해주셔서 감사합니다.")

비밀번호를 입력하세요: 삼 사 오오오오
올바른 비밀번호 형식이 아닙니다.
이용해주셔서 감사합니다.


#### 사용자 정의 예외처리
    - python에서는 예외가 아니나 사용자가 조건을 설정하여 예외를 발생시켜 비정상종료 시키는 방법
    - 오버라이딩 또는 새로운 클래스 선언을 통해 생성

In [50]:
class LowNumber(Exception):
    def __str__(self):
        return "조건이 맞지 않습니다."

def pw_input():
    num = sum(map(int, input("비밀번호를 입력하세요: ").split(" ")))
    if num < 50:
        raise LowNumber()
    print(num)

In [52]:
pw_input()

비밀번호를 입력하세요: 48 1 1 1
51
